services:
  db:
    container_name: database
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    # ports:
      # - "5432:5432"
    networks:
      - backend

  api:
    container_name: app
    image: pedrostanzani/jwt-auth-api:latest
    # build:
    #   context: ./app
    #   dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/postgres}
      JWT_SECRET: ${JWT_SECRET:-fbb15a424da0317fada92aca9512af0520f4f556cc0a96e12a9711324f45f350}
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backend

networks:
  backend:
